### PR TITLE
chore: correcting few mistakes in documentation

### PR DESCRIPTION
**Pull request by IssouChancla**
Hey, found few errors in the documentation while reading it, should be good now.
Doesn't require testing or changelog entry.

### CODE REVIEW

**Comment by CPerezz** [comment]
Another of these bots trying to collect airdrops for fake GH collaborations LOL.
It's out of hand.

@ed255 @davidnevadoc  I remember we discussed that. What shall we do?

**Comment by ed255** [comment]
> Another of these bots trying to collect airdrops for fake GH collaborations LOL. It's out of hand.
> 
> @ed255 @davidnevadoc I remember we discussed that. What shall we do?

I think they may not be bots (although it's hard to figure out).  If we believe they are not bots, and the typo fixes are correct, I think it's OK to merge the PR.

**Comment by CPerezz** [comment]
> I think they may not be bots (although it's hard to figure out). If we believe they are not bots, and the typo fixes are correct, I think it's OK to merge the PR.

Why having a private commit history then? Looks sus @ed255

**Comment by ed255** [comment]
> > I think they may not be bots (although it's hard to figure out). If we believe they are not bots, and the typo fixes are correct, I think it's OK to merge the PR.
> 
> Why having a private commit history then? Looks sus @ed255

I assume this user is recent, and has a bunch of open PRs of the same kind, and that may be why they keep their profile private.

**Review by CPerezz — APPROVED** [review]
Alright @ed255 !

LGTM

**Pull request merged**
