### PR TITLE
patch: include more fields to transcript

### LINKED ISSUE #350: Include more fields within `transcript` prior to a new major version release
> A small note: since any change to this function makes the `transcript_repr` different, I think it'd be good to also includes other conditionally debugged fields in futher PRs before the next release, to avoid needs of rotating vk.

Originally posted by @han0110 in https://github.com/privacy-scaling-explorations/halo2/pull/348#pullrequestreview-2099352124

### PR DESCRIPTION
**Pull request by guorong009**
## Description
- Add more conditionally-debugged fields to `transcript_repr`

## Related issues
- Resolve #350 

## Changes
- add multi-phase related challenge fields to `PinnedConstraintSystem::fmt`
- update the `plonk_api` test

### CODE REVIEW

**Review by ed255 — APPROVED** [review]
LGTM!

**Review by han0110 — APPROVED** [review]
LGTM!

**Comment by guorong009** [comment]
@ed255 @han0110 
Before I merge the PR, can you check if any more fields should be added to `transcript_repr`?
If you think no more, then I will merge the PR.

**Comment by han0110** [comment]
I think this is all, but I just realized we could just bring back the `#[derive(Debug)]` like [in upstream](https://github.com/zcash/halo2/blob/7df93fd855395dcdb301a857d4b33f37903bbf76/halo2_proofs/src/plonk/circuit.rs#L969-L971), so we are sure we will not miss any fields.

**Pull request merged**
