### PR TITLE
Host docs ghpages

### PR DESCRIPTION
**Pull request by thogiti**
Created a github action workflow to host the docs on to github pages. Added an `index.html` at the root of `docs` folder.

### CODE REVIEW

**Comment by thogiti** [comment]
Hello @CPerezz. I am a ZK Fellow from PSE's summer ZK Fellow program. 

#140 

I completed this task and now we can see the PSE's docs on github pages host. You can test it here:

https://thogiti.github.io/halo2/halo2/

I added a workflow through Github action to automate building the docs from PSE's root repo, add necessary index.html file in the correct path and deploy to github pages. 

https://github.com/thogiti/halo2/blob/main/.github/workflows/docs-ghpages.yml

I also opened a PR on PSE's halo2 repo. If it is approved then I can update the link to the documentation from the main repo as a separate contribution.

**Review by CPerezz — APPROVED** [review]
LGTM. 

Will activate gh pages now and set it to `docs` folder.
Thanks for the PR!

**Review by ChihChengLiang — APPROVED** [review]
LGTM.

**Comment by CPerezz** [comment]
@ChihChengLiang let's make sure that in the next deployment everything works smoothly!

**Pull request merged**
