### PR TITLE
BN254 Support for Poseidon instance p128pow5t3

### PR DESCRIPTION
**Pull request by LiuJiazheng**
Add MDS, Constants, TestVectors compatible with Fr (BN254 Curve Scalar Field)

Rationale: This helps if someone wants to use KZG scheme to generate proof, meanwhile still using Poseidon instance p128pow5t3 in their circuits.

### CODE REVIEW

**Review by CPerezz — CHANGES_REQUESTED** [review]
This isn't generic enough.  As basically, `Fr` can be anything not just `bn256`.

If we want to support constants for more curves, we should try to modify the traits to that this can happen propperly. Adding traits that handle theese constants for each curve.

**Comment by LiuJiazheng** [comment]
> This isn't generic enough. As basically, `Fr` can be anything not just `bn256`.
> 
> If we want to support constants for more curves, we should try to modify the traits to that this can happen propperly. Adding traits that handle theese constants for each curve.

Could you please elaborate a bit? Is that suggesting to create a template to do meta-programming stuffs? Since the pattern is pretty clear here. 

Or just a naming issue?

**Comment by CPerezz** [comment]
Nonono no meta-programming. I just meant that we should provide an interface/trait so that we can have an impl for all the curves for it. Hence, if anyone wants to use this, needs to find the proper parameters and make a PR with the trait impl.

**Comment by LiuJiazheng** [comment]
Have merged it to latest and fix fmt/clippy issue

**Comment by CPerezz** [comment]
Closing as we will not be able to maintain or improve the additions to `halo2_gadgets`

Thanks for the PR @LiuJiazheng and sorry for the outcome of it.

**Pull request closed without merging**
